# A generic, single database configuration for Alembic migrations.

[alembic]
# Path to migration scripts
script_location = alembic

# Template used to generate migration file names; default date format is used.
file_template = %%(rev)s_%%(slug)s

# Prepend current working directory to sys.path
prepend_sys_path = .

# Timezone to use when rendering the date within the migration file as well as the filename.
# timezone =

# Max length of characters to apply to the "slug" field
# truncate_slug_length = 40

# Set to 'true' to run the environment during the 'revision' command, regardless of autogenerate
# revision_environment = false

# Set to 'true' to allow .pyc and .pyo files without a source .py file to be detected as revisions in the versions/ directory
# sourceless = false

# Version location specification; this defaults to alembic/versions.
version_locations = alembic/versions

# Version path separator; default is os.pathsep.
# version_path_separator = :

# Set to 'true' to search source files recursively in each "version_locations" directory
# recursive_version_locations = false

# The output encoding used when revision files are written from script.py.mako
# output_encoding = utf-8

sqlalchemy.url = postgresql+psycopg://postgres:postgres@localhost:5432/patchpilot

[post_write_hooks]
# Post-write hooks define scripts or Python methods that are run on newly generated revision scripts.

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
